In [1]:
import numpy as np, matplotlib as plt
import numpy as np

2018 05 30
-----------

to do's:
- [ ] Analysiere Impedanz Daten von $D_0 = 1e-12 $ Simulationen von model 0
    + [ ] Diffusionskoeffizient variiert
    + [ ] Sepearator length variiert

- [ ] schreibe export funktion die setup und daten in class zusammenfässt und speichert
- [ ] schreibe multiprocessing funktion für simulation für parameter sweep
- [ ] parameter sweep für model 1
   

In [1]:
# teste class save with data
import numpy as np

class testclass( object ):
    
    def __init__( self, parameter ):
        """
        Void
        """
        self.parameter = parameter

    def set_data( self, data ):
        """
        Void
        """
        self.data = data

In [11]:

testdata = np.random.rand(10)

# init testclass with parameter
parameter = float(5.0)

instance = testclass( parameter )

# set data 
instance.set_data( testdata )

print(instance.__dict__)

{'parameter': 5.0, 'data': array([0.51225322, 0.99571188, 0.72854996, 0.15526514, 0.50523882,
       0.78370446, 0.52142716, 0.6385576 , 0.6078745 , 0.95217333])}


In [13]:
# save whole class in file
import pickle

with open("test.obj", "wb") as file_id:
    pickle.dump(instance, file_id)

In [2]:
# test recover old data after restarting kernel
import pickle

filename = r"test.obj"

with open(filename, "rb") as f_id:
    class_instance = pickle.load(f_id)


In [5]:
# test class instance
print(class_instance.__dict__)
print(type(class_instance.data))

{'parameter': 5.0, 'data': array([0.51225322, 0.99571188, 0.72854996, 0.15526514, 0.50523882,
       0.78370446, 0.52142716, 0.6385576 , 0.6078745 , 0.95217333])}
<class 'numpy.ndarray'>


Setup class mit den daten wie zuvor

In [6]:
# get aktuelles datum, um simulation zuordnent zu können
from datetime import date

print(str(date.today()))

2018-05-30


In [32]:
# kwargs
testdict = {"filename" : "test", "bla" :1}
print(testdict)

bla = None
if not bla is None:
    print(bla)

{'filename': 'test', 'bla': 1}


In [104]:
# test new setup class
stp1 = Setup(  I = 500,
		            N = 2 ** 20,
		            Dt = 1e-4,
		            T = 300,
		            L = 10,
		            lengthscale = 1e9,
		            c0_in = 1.0,
		            DA = 1.0,
		            DC = 2.0,
		            D0_in = 1e-12,
		            epsilon = 1.0,
		            epsilon_m = 80.0,
		            testname = "imp_diff_1",
    	            model = 0,
                   out_method = "c_only")

testdata = np.random.rand(10)

# test save current to setup obj
stp1.set_current_data( testdata )

stp1.__dict__.get("current_data")

array([921.00042628, 933.82773972, 156.77960192, 835.12522959,
       639.89082014, 112.83631804, 307.49891943,  99.14673004,
       118.05842747, 143.58444581])

In [51]:
# teste save method

stp1.save("testi")

# --> klappt

Brauche: init methode zum instanzieren von setup obj mit daten

In [54]:
# test load from .sim file
obj = Setup.load_setup("testi.sim")
print(obj.__dict__ )
print(stp1.__dict__ )
# --> works

In [64]:
from pre_fun import createVoltage

In [113]:
# Kovertiere bestehende simulationen zu den class instances
path = r"M:\QMR\Abteilungsprojekte\FG\local\masterthesis\test_environment\old_impl\pc1"
filename_list = [ r"\imp_diff_1_current.npy",  r"\imp_diff_2_current.npy",
                 r"\imp_diff_3_current.npy", r"\imp_diff_4_current.npy"]

current2 = np.load(path + filename_list[3])

stp2 = Setup( 	I = 500,
	             	N = 2 ** 20,
	             	Dt = 1e-4,
	     	        T = 300,
	 	            L = 10,
	 	            lengthscale = 1e9,
		            c0_in = 1.0,
		            DA = 1.0,
		            DC = 20.0,
		            D0_in = 1e-12,
		            epsilon = 1.0,
		            epsilon_m = 80.0,
		            testname = "imp_diff_4",
		            model = 0,
		            out_method = "c_only" )

voltage, t = createVoltage( stp2, 0.2 )

stp2.set_current_data( current2 )

stp2.set_input_voltage_data( voltage )

stp2.save()

Min Freq, Frequency Resolution Df [Hz]:  95.367431640625
Min Freq, Frequency Resolution Df [None]:  0.0095367431640625
Maximal Frequency, Nyquist [Hz]:  45454545.454545446
Maximal Frequency, Nyquist [None]:  4545.454545454545
Number of Points:  1048576
Total Amplitude [mV]:  9.812537392585208


In [110]:
stp2.input_voltage_data.max() - stp2.input_voltage_data.min()

0.009812537392585207

In [96]:
seti = Setup.load_setup("imp_diff_4.sim")

In [97]:
seti.current_data == current2

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

Automatic conversion of simulated impedance currents to mA/cm^2

In [98]:
seti.__dict__

{'D0': 1000000.0,
 'DA': 1.0,
 'DC': 20.0,
 'Dt': 0.0001,
 'I': 500,
 'L': 10,
 'N': 1048576,
 'T': 300,
 'T0': 0.0001,
 'c0': 0.6022140857,
 'chi1': 1.0,
 'chi2': 526.9004702828952,
 'current_data': array([[ 0.        ,  0.        ,  0.89272907, ...,  0.38704121,
         -0.49089858,  0.76978086],
        [ 0.        ,  0.        , -0.8927123 , ..., -0.38705012,
          0.49088382, -0.76978637]]),
 'epsilon': 1.0,
 'epsilon_m': 80.0,
 'input_voltage_data': array([ 0.        ,  0.07865603,  0.05970851, ..., -0.07155604,
        -0.05970851, -0.07865603]),
 'lengthscale': 1000000000.0,
 'model': 0,
 'out_method': 'c_only',
 'phi0': 0.025851991011651636,
 'simulation_date': '2018-05-30',
 'testname': 'imp_diff_4'}

2018 05 31
-------------

To dos:

- [X] Schreibe Solver für single voltage pertubation
       + [ ] vllt. optional **kwarg argument ?
       + [X] mod setup class --> soll auch sol daten speichern
- [X] mod setup class: wenn randbedingugnen gegeben sind, dann muss auch model parameter auf 1,2

Wie verändert sich equilibrium bei model 1?
- [ ] 

12.49861111111111

In [138]:
class Setup():
    """


    Simulation Types:
        - single_const:

            Constant

        c_only_imp

        full_imp


    """
    ELE_CHARGE = 1.6021766208e-19 # [Coulomb], constant value
    AVOGADRO_CONST = 6.022140857e23 # [1/mol]
    EPSILON_VAC = 8.854187817e-12 # original value in [Farad/m],
    BOLTZMANN_CONST = 1.38064852e-23 # [Joule/Kelvin], constant value


    def __init__( self, I, N, Dt, T, L, lengthscale, c0_in, DA, DC, D0_in, 
                 epsilon, epsilon_m, testname, model, sim_method, kA, kC, foxA, foxC, **kwargs ):

        self.I = I
        self.N = N
        self.Dt = Dt
        self.T = T
        self.L = L
        self.lengthscale = lengthscale
        self.c0 = c0_in * self.AVOGADRO_CONST * 1e3 * ( lengthscale ) ** (-3)
        self.DA = DA
        self.DC = DC
        self.D0 = D0_in * (lengthscale ) ** 2
        self.epsilon = epsilon
        self.epsilon_m = epsilon_m
        self.testname = testname

        # reaction boundary conditions
        self.kA = kA
        self.kC = kC
        self.foxA = foxA
        self.foxC = foxC

        # possible output method:
        #                        - full: saves current and full solution vector
        #                        - c_only: saves only current, avoid saving whole solution in order to save memory

        self.sim_method = sim_method

        self.phi0 = ( self.BOLTZMANN_CONST * T) / self.ELE_CHARGE

        self.chi2 = ( self.c0 * lengthscale * (self.ELE_CHARGE * self.L) ** 2 /
                     (self.epsilon_m * self.EPSILON_VAC * self.BOLTZMANN_CONST * T) )

        self.chi1 = 1.0

        self.T0 = self.L ** 2 / self.D0
        
        # call setter methods
        self.set_ref_flux()
        
        # call setter method for model
        self.set_model( model )
        
        # keyword args
        self.steady_state_tol = kwargs.get('steady_state_tol', 1e-7)
           
#--------- setter methods ------------------------------------------------------------
    def set_ref_flux( self ):
        
        self.f0 = self.L * self.c0 / self.T0
    
    def set_model( self, model ):
        """
        Setter method for model
        Void
        """
        test_attr = ['kA', 'kC', 'foxA', 'foxC']
        logical_list = []
        
        if model == 0:
            
            for element in test_attr:
            
                try:
                
                    if not getattr( self, element) == 0:
                    
                        raise ValueError('Model and boundary conditiosn mismatch!')
                
                except AttributeError:
                    
                    pass
                
            self.model = model
                    
        else:
            
            for element in test_attr:
            
                try:
                
                    if getattr( self, element) == 0:
                    
                        logical_list.append(True)
                
                except AttributeError:
                    
                    self.model = model
            
            if logical_list.__len__() == test_attr.__len__():
                
               raise ValueError('Model and boundary conditions mismatch!')
            
            else:
                
                self.model = model    
    
#----- setter methods for simulation data ------------------------------------------------------------
    def set_current_data( self, current ):
        """
        Save simulated current data automatically converted to mA / cm^2
        Void
        """
        
        # check input
        if not isinstance(current, np.ndarray):
            
            raise TypeError("Current data is not Numpy array!")
        
        # automatically convert to mA / cm^2
        self.current_data = current * self.f0 * self.ELE_CHARGE * 1e17
        self.simulation_date = str(date.today())
        
    def set_input_voltage_data( self, voltage, nondim = True ):
        """
        Create pertubation voltage data automatically converted to V
        Void
        """
        
        # check input        
        if isinstance( voltage, np.ndarray ):
            
            if nondim == True:

                self.input_voltage_data = voltage / self.phi0
            
            else:

                self.input_voltage_data = voltage

        elif isinstance( voltage, float ):
            """
            Works for single_const sim method
            """
            # check sim_method
            if self.sim_method == 'single_const':

                # allocate
                self.input_voltage_data = np.zeros( self.N, dtype = np.float64)

                if nondim == True:
                    
                    self.input_voltage_data += voltage / self.phi0

                else:

                    self.input_voltage_data += voltage

            else:
                
                raise ValueError('Voltage input and sim method mismatch!')
    
        else:
            
            raise TypeError("Wrong data type for voltage input!")
            
        
        
    def set_sol_data( self, sol ):
        """
        Save solution matrix. Automatic convert to M and mV
        Void
        """
        
        # check input
        if not isinstance(sol, np.ndarray):
            
            raise TypeError("Sol data is not Numpy array!")
        
        # convert to potential to mV
        sol[2*self.I:3*self.I,:] *= self.phi0 * 1e3
        
        self.sol_data = sol

#------- load and save methods -------------------------------------------------------------------
    @classmethod
    def load_setup( cls, filename ):
        """
        Load setup object from .sim file with 'pickle' and return class instance with data
        """
        if not isinstance(filename, str):

                raise TypeError("Optional filename is not a string!")
        
        with open(filename, "rb") as f_id:
            class_instance = pickle.load(f_id)
        
        return class_instance
    
    def save( self, filename_in = None ):
        """
        Save setup object including all data using pickle as obj file.
        Void
        """
        if filename_in is None:
            
            filename = self.testname + ".sim"
            
        else:
        
            # check if filename is a string
            if not isinstance(filename_in, str):

                raise TypeError("Optional filename is not a string!")
            
            else:
                
                filename = filename_in + ".sim"
        
        
        with open(filename, "wb") as file_id:
            pickle.dump( self, file_id)

#--------- simulation related methods -------------------------------------------------------------
    def create_time_axis( self,):
        """
        Create time axis from a instance with given N and Dt
        """
        
        # create time axis
        t = np.zeros(N, dtype = np.float64)
        for j in range(0,N):

            t[j] = j * Dt
            
        return t,

In [ ]:
# teste set tolerance für solver 

In [115]:
# Test numpy multiplication without copying and slicing
a = np.ones([3,3], dtype = np.float64)

a[0:2,:] *= 5
print(a)

[[5. 5. 5.]
 [5. 5. 5.]
 [1. 1. 1.]]


In [121]:
# Teste sim type mit single_constant voltage

def single_const( U0, phi0, N ):

    # allocate
    volt = np.zeros(N, dtype = np.float64)
    
    volt[1:] += U0 / phi0
    
    return volt

U0 = 0.010
N = 100
phi0 = 0.025
phiC = single_const(U0, phi0, N)

print(phiC)

[0.  0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4
 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4
 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4
 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4
 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4
 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]


In [ ]:
# getter method for voltage


In [137]:
stp4 = Setup(  I = 500,
                    N = 2 ** 5,
                    Dt = 1e-4,
                    T = 300,
                    L = 10,
                    lengthscale = 1e9,
                    c0_in = 1.0,
                    DA = 1.0,
                    DC = 2.0,
                    D0_in = 1e-12,
                    epsilon = 1.0,
                    epsilon_m = 80.0,
                    testname = "imp_model_1_4",
                    model = 1,
                   sim_method = "single_const",
                   kA = 1e1,
                   kC = 1e1,
                   foxA = 0.5e1,
                   foxC = 0.05e1,
                   testtype = "impedance" )

stp4.set_input_voltage_data( np.ones(10))

stp4.input_voltage_data

array([0.02585199, 0.02585199, 0.02585199, 0.02585199, 0.02585199,
       0.02585199, 0.02585199, 0.02585199, 0.02585199, 0.02585199])

In [148]:
a = np.random.rand(10)

for j in range(9):
    print(j)
    a[j] += j
    

print(a)
print(a[:j+1])
print(a[:j+1].size)
print(j)
b = a[:j+1]
print(b)

0
1
2
3
4
5
6
7
8
[0.4644     1.22383677 2.17921637 3.97033279 4.12467304 5.00664251
 6.05038755 7.87214735 8.69402423 0.89367846]
[0.4644     1.22383677 2.17921637 3.97033279 4.12467304 5.00664251
 6.05038755 7.87214735 8.69402423]
9
8
[0.4644     1.22383677 2.17921637 3.97033279 4.12467304 5.00664251
 6.05038755 7.87214735 8.69402423]


In [154]:
a = a[5:]

print(a)

[5.00664251 6.05038755 7.87214735 8.69402423 0.89367846]


In [160]:
def test(a, nondim = True):
    
    if nondim == False:
        b = np.ones(5) * a / 10
    else:
        b = np.ones(5) * a * 10
    
    return b

test(5, nondim = False)

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [ ]:
# set pertubation voltage
stp4.set_input_voltage_data( 10e-3 )


t1 = clock()

# start multiprocessing
mp.Process( target = solver, args = ( stp4, ))
# p2 = mp.Process( target = solver, args = ( stp2, reaction_bc, phiC, ))
# p3 = mp.Process( target = solver, args = ( stp3, reaction_bc, phiC, ))
# p4 = mp.Process( target = solver, args = ( stp4, reaction_bc, phiC, ))

# start single processes
p1.start()
# p2.start()
# p3.start()
# p4.start()

# wait until processes are finished
p1.join()
# p2.join()
# p3.join()
# p4.join()

t2 = clock()

print("Overall Simulation Time [s]: ", (t2 - t1)  )

In [190]:
a = [ np.ones(5), 6* np.ones(5), ]


max([ el[0:2].max() for el in a ])
    

6.0

01.06.2018
------------

In [9]:
Dt = 0.1
N = 10

print(np.arange(0,N, Dt))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
